baseURL = "http://example.org/"
languageCode = "en-us"
title = "Stu's Cool Cat Site"
googleAnalytics = "UA-xxxxxxxxxxxx"
theme = "basic"
[params]
    author = "Stuart Marsh"
    description = "Stuart Marsh's Portfolio Website"